// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.electrobright.electrobright_app

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object PlatformApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Semantic haptic events. Each platform maps an event to its best native
 * rendering (see HapticsHost.swift / HapticsHost.kt).
 */
enum class HapticEvent(val raw: Int) {
  /** Tab, segment or mode-tile snap. */
  SELECTION(0),
  /** 10 % slider step or dial detent. */
  DETENT(1),
  /** Slider end stop (0 % / 100 %). */
  EDGE(2),
  /** Colour wheel passing a 30° hue mark. */
  HUE_DETENT(3),
  /** Colour wheel passing a primary hue (red, green, blue). */
  HUE_DETENT_STRONG(4),
  POWER_ON(5),
  POWER_OFF(6),
  SUCCESS(7),
  WARNING(8),
  ERROR(9),
  PRESET_LOADED(10),
  CONNECTED(11),
  LONG_PRESS(12);

  companion object {
    fun ofRaw(raw: Int): HapticEvent? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BluetoothAuthorization(val raw: Int) {
  /** The user has not been asked yet. */
  NOT_DETERMINED(0),
  /** Blocked by the system (parental controls / MDM). */
  RESTRICTED(1),
  DENIED(2),
  ALLOWED(3),
  /** The device has no Bluetooth LE. */
  UNSUPPORTED(4);

  companion object {
    fun ofRaw(raw: Int): BluetoothAuthorization? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class SettingsPage(val raw: Int) {
  APP(0),
  BLUETOOTH(1),
  LOCATION(2);

  companion object {
    fun ofRaw(raw: Int): SettingsPage? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DisplayInfo (
  val refreshRate: Double,
  val maxRefreshRate: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DisplayInfo {
      val refreshRate = pigeonVar_list[0] as Double
      val maxRefreshRate = pigeonVar_list[1] as Double
      return DisplayInfo(refreshRate, maxRefreshRate)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      refreshRate,
      maxRefreshRate,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DisplayInfo
    return PlatformApiPigeonUtils.deepEquals(this.refreshRate, other.refreshRate) && PlatformApiPigeonUtils.deepEquals(this.maxRefreshRate, other.maxRefreshRate)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.refreshRate)
    result = 31 * result + PlatformApiPigeonUtils.deepHash(this.maxRefreshRate)
    return result
  }
  override fun toString(): String {
    return "DisplayInfo(refreshRate=$refreshRate, maxRefreshRate=$maxRefreshRate)"
  }
}
private open class PlatformApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          HapticEvent.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BluetoothAuthorization.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          SettingsPage.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DisplayInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is HapticEvent -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is BluetoothAuthorization -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is SettingsPage -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is DisplayInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface HapticsHostApi {
  /** Warms the haptic engine for an imminent gesture (call on touch-down). */
  fun prepare(event: HapticEvent)
  /** Plays [event] at [intensity] (0..1, already scaled by the user setting). */
  fun play(event: HapticEvent, intensity: Double)

  companion object {
    /** The codec used by HapticsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
    /** Sets up an instance of `HapticsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HapticsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.electrobright.HapticsHostApi.prepare$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventArg = args[0] as HapticEvent
            val wrapped: List<Any?> = try {
              api.prepare(eventArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.electrobright.HapticsHostApi.play$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val eventArg = args[0] as HapticEvent
            val intensityArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.play(eventArg, intensityArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PlatformHostApi {
  /** Current Bluetooth permission, read WITHOUT showing any system prompt. */
  fun bluetoothAuthorization(): BluetoothAuthorization
  /**
   * Shows the system permission prompt when the state is notDetermined and
   * returns the result (iOS: via a short-lived CBCentralManager).
   */
  suspend fun requestBluetoothAuthorization(): BluetoothAuthorization
  /**
   * Android: asks the user to switch Bluetooth on (system dialog).
   * iOS: not possible; returns false.
   */
  suspend fun requestEnableBluetooth(): Boolean
  /** Android 11 and older need Location Services on to scan for BLE devices. */
  fun locationServicesRequiredButOff(): Boolean
  /** Opens a system settings page (iOS always opens the app's page). */
  fun openSettings(page: SettingsPage)
  /** iOS "Reduce Transparency"; Android has no equivalent (false). */
  fun reduceTransparency(): Boolean
  /** iOS: UIApplication.beginBackgroundTask; returns -1 when unsupported. */
  fun beginBackgroundTask(name: String): Long
  fun endBackgroundTask(id: Long)
  fun displayInfo(): DisplayInfo

  companion object {
    /** The codec used by PlatformHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
    /** Sets up an instance of `PlatformHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PlatformHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.electrobright.PlatformHostApi.bluetoothAuthorization$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.bluetoothAuthorization())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.electrobright.PlatformHostApi.requestBluetoothAuthorization$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestBluetoothAuthorization())
              } catch (exception: Throwable) {
                PlatformApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.electrobright.PlatformHostApi.requestEnableBluetooth$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.requestEnableBluetooth())
              } catch (exception: Throwable) {
                PlatformApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.electrobright.PlatformHostApi.locationServicesRequiredButOff$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.locationServicesRequiredButOff())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.electrobright.PlatformHostApi.openSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pageArg = args[0] as SettingsPage
            val wrapped: List<Any?> = try {
              api.openSettings(pageArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.electrobright.PlatformHostApi.reduceTransparency$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.reduceTransparency())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.electrobright.PlatformHostApi.beginBackgroundTask$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nameArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.beginBackgroundTask(nameArg))
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.electrobright.PlatformHostApi.endBackgroundTask$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.endBackgroundTask(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.electrobright.PlatformHostApi.displayInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.displayInfo())
            } catch (exception: Throwable) {
              PlatformApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PlatformEventsApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PlatformEventsApi. */
    val codec: MessageCodec<Any?> by lazy {
      PlatformApiPigeonCodec()
    }
  }
  suspend fun onReduceTransparencyChanged(enabledArg: Boolean)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.electrobright.PlatformEventsApi.onReduceTransparencyChanged$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(enabledArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(PlatformApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
  /** The OS is about to end background task [id]; clean up immediately. */
  suspend fun onBackgroundTaskExpiring(idArg: Long)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.electrobright.PlatformEventsApi.onBackgroundTaskExpiring$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(idArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(PlatformApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
