// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum PlatformApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Semantic haptic events. Each platform maps an event to its best native
/// rendering (see HapticsHost.swift / HapticsHost.kt).
enum HapticEvent: Int, CaseIterable {
  /// Tab, segment or mode-tile snap.
  case selection = 0
  /// 10 % slider step or dial detent.
  case detent = 1
  /// Slider end stop (0 % / 100 %).
  case edge = 2
  /// Colour wheel passing a 30° hue mark.
  case hueDetent = 3
  /// Colour wheel passing a primary hue (red, green, blue).
  case hueDetentStrong = 4
  case powerOn = 5
  case powerOff = 6
  case success = 7
  case warning = 8
  case error = 9
  case presetLoaded = 10
  case connected = 11
  case longPress = 12
}

enum BluetoothAuthorization: Int, CaseIterable {
  /// The user has not been asked yet.
  case notDetermined = 0
  /// Blocked by the system (parental controls / MDM).
  case restricted = 1
  case denied = 2
  case allowed = 3
  /// The device has no Bluetooth LE.
  case unsupported = 4
}

enum SettingsPage: Int, CaseIterable {
  case app = 0
  case bluetooth = 1
  case location = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct DisplayInfo: Hashable, CustomStringConvertible {
  var refreshRate: Double
  var maxRefreshRate: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DisplayInfo? {
    let refreshRate = pigeonVar_list[0] as! Double
    let maxRefreshRate = pigeonVar_list[1] as! Double

    return DisplayInfo(
      refreshRate: refreshRate,
      maxRefreshRate: maxRefreshRate
    )
  }
  func toList() -> [Any?] {
    return [
      refreshRate,
      maxRefreshRate,
    ]
  }
  static func == (lhs: DisplayInfo, rhs: DisplayInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return PlatformApiPigeonInternal.deepEquals(lhs.refreshRate, rhs.refreshRate) && PlatformApiPigeonInternal.deepEquals(lhs.maxRefreshRate, rhs.maxRefreshRate)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DisplayInfo")
    PlatformApiPigeonInternal.deepHash(value: refreshRate, hasher: &hasher)
    PlatformApiPigeonInternal.deepHash(value: maxRefreshRate, hasher: &hasher)
  }

  public var description: String {
    return "DisplayInfo(refreshRate: \(String(describing: refreshRate)), maxRefreshRate: \(String(describing: maxRefreshRate)))"
  }
}

private class PlatformApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HapticEvent(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BluetoothAuthorization(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SettingsPage(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return DisplayInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PlatformApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HapticEvent {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BluetoothAuthorization {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? SettingsPage {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? DisplayInfo {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PlatformApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PlatformApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PlatformApiPigeonCodecWriter(data: data)
  }
}

class PlatformApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PlatformApiPigeonCodec(readerWriter: PlatformApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HapticsHostApi {
  /// Warms the haptic engine for an imminent gesture (call on touch-down).
  func prepare(event: HapticEvent) throws
  /// Plays [event] at [intensity] (0..1, already scaled by the user setting).
  func play(event: HapticEvent, intensity: Double) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HapticsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PlatformApiPigeonCodec.shared }
  /// Sets up an instance of `HapticsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HapticsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Warms the haptic engine for an imminent gesture (call on touch-down).
    let prepareChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.electrobright.HapticsHostApi.prepare\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prepareChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventArg = args[0] as! HapticEvent
        do {
          try api.prepare(event: eventArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      prepareChannel.setMessageHandler(nil)
    }
    /// Plays [event] at [intensity] (0..1, already scaled by the user setting).
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.electrobright.HapticsHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let eventArg = args[0] as! HapticEvent
        let intensityArg = args[1] as! Double
        do {
          try api.play(event: eventArg, intensity: intensityArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PlatformHostApi {
  /// Current Bluetooth permission, read WITHOUT showing any system prompt.
  func bluetoothAuthorization() throws -> BluetoothAuthorization
  /// Shows the system permission prompt when the state is notDetermined and
  /// returns the result (iOS: via a short-lived CBCentralManager).
  func requestBluetoothAuthorization() async throws -> BluetoothAuthorization
  /// Android: asks the user to switch Bluetooth on (system dialog).
  /// iOS: not possible; returns false.
  func requestEnableBluetooth() async throws -> Bool
  /// Android 11 and older need Location Services on to scan for BLE devices.
  func locationServicesRequiredButOff() throws -> Bool
  /// Opens a system settings page (iOS always opens the app's page).
  func openSettings(page: SettingsPage) throws
  /// iOS "Reduce Transparency"; Android has no equivalent (false).
  func reduceTransparency() throws -> Bool
  /// iOS: UIApplication.beginBackgroundTask; returns -1 when unsupported.
  func beginBackgroundTask(name: String) throws -> Int64
  func endBackgroundTask(id: Int64) throws
  func displayInfo() throws -> DisplayInfo
  /// Android: asks for the display's highest refresh rate while [high]
  /// (something moves or a finger is down); otherwise leaves the rate to
  /// the system. iOS: nothing (ProMotion adapts on its own).
  func setHighRefreshRate(high: Bool) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PlatformHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PlatformApiPigeonCodec.shared }
  /// Sets up an instance of `PlatformHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PlatformHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Current Bluetooth permission, read WITHOUT showing any system prompt.
    let bluetoothAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.electrobright.PlatformHostApi.bluetoothAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      bluetoothAuthorizationChannel.setMessageHandler { _, reply in
        do {
          let result = try api.bluetoothAuthorization()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      bluetoothAuthorizationChannel.setMessageHandler(nil)
    }
    /// Shows the system permission prompt when the state is notDetermined and
    /// returns the result (iOS: via a short-lived CBCentralManager).
    let requestBluetoothAuthorizationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.electrobright.PlatformHostApi.requestBluetoothAuthorization\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestBluetoothAuthorizationChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.requestBluetoothAuthorization()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestBluetoothAuthorizationChannel.setMessageHandler(nil)
    }
    /// Android: asks the user to switch Bluetooth on (system dialog).
    /// iOS: not possible; returns false.
    let requestEnableBluetoothChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.electrobright.PlatformHostApi.requestEnableBluetooth\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestEnableBluetoothChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.requestEnableBluetooth()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestEnableBluetoothChannel.setMessageHandler(nil)
    }
    /// Android 11 and older need Location Services on to scan for BLE devices.
    let locationServicesRequiredButOffChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.electrobright.PlatformHostApi.locationServicesRequiredButOff\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      locationServicesRequiredButOffChannel.setMessageHandler { _, reply in
        do {
          let result = try api.locationServicesRequiredButOff()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      locationServicesRequiredButOffChannel.setMessageHandler(nil)
    }
    /// Opens a system settings page (iOS always opens the app's page).
    let openSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.electrobright.PlatformHostApi.openSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openSettingsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pageArg = args[0] as! SettingsPage
        do {
          try api.openSettings(page: pageArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openSettingsChannel.setMessageHandler(nil)
    }
    /// iOS "Reduce Transparency"; Android has no equivalent (false).
    let reduceTransparencyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.electrobright.PlatformHostApi.reduceTransparency\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      reduceTransparencyChannel.setMessageHandler { _, reply in
        do {
          let result = try api.reduceTransparency()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      reduceTransparencyChannel.setMessageHandler(nil)
    }
    /// iOS: UIApplication.beginBackgroundTask; returns -1 when unsupported.
    let beginBackgroundTaskChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.electrobright.PlatformHostApi.beginBackgroundTask\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      beginBackgroundTaskChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        do {
          let result = try api.beginBackgroundTask(name: nameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      beginBackgroundTaskChannel.setMessageHandler(nil)
    }
    let endBackgroundTaskChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.electrobright.PlatformHostApi.endBackgroundTask\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      endBackgroundTaskChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let idArg = args[0] as! Int64
        do {
          try api.endBackgroundTask(id: idArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      endBackgroundTaskChannel.setMessageHandler(nil)
    }
    let displayInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.electrobright.PlatformHostApi.displayInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      displayInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.displayInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      displayInfoChannel.setMessageHandler(nil)
    }
    /// Android: asks for the display's highest refresh rate while [high]
    /// (something moves or a finger is down); otherwise leaves the rate to
    /// the system. iOS: nothing (ProMotion adapts on its own).
    let setHighRefreshRateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.electrobright.PlatformHostApi.setHighRefreshRate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setHighRefreshRateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let highArg = args[0] as! Bool
        do {
          try api.setHighRefreshRate(high: highArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setHighRefreshRateChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PlatformEventsApiProtocol {
  @MainActor func onReduceTransparencyChanged(enabled enabledArg: Bool) async throws
  /// The OS is about to end background task [id]; clean up immediately.
  @MainActor func onBackgroundTaskExpiring(id idArg: Int64) async throws
}
class PlatformEventsApi: PlatformEventsApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PlatformApiPigeonCodec {
    return PlatformApiPigeonCodec.shared
  }
  @MainActor func onReduceTransparencyChanged(enabled enabledArg: Bool) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.electrobright.PlatformEventsApi.onReduceTransparencyChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([enabledArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
  /// The OS is about to end background task [id]; clean up immediately.
  @MainActor func onBackgroundTaskExpiring(id idArg: Int64) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.electrobright.PlatformEventsApi.onBackgroundTaskExpiring\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([idArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
