#!/usr/bin/env bash
# Bundles the firmware images into the app:
# - the wireless-update image (firmware/tools/build_update_image.sh) in
#   app/assets/firmware/ with manifest.json (version, size, SHA-256, product,
#   image kind, file). The app reads the manifest at start;
#   test/cross_repo/firmware_bundle_test.dart checks it against the file and
#   the firmware version constant.
# - the two rollback test images (--rollback-test fail|freeze) as generated
#   Dart data, lib/features/developer/rollback_test_images.g.dart (zlib +
#   base64). Only debug builds reach it (rollback_test.dart), so profile and
#   release builds contain neither the images nor the option.
#
#   tool/bundle_firmware.sh
set -euo pipefail

APP="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="$(cd "$APP/.." && pwd)"
DEST="$APP/assets/firmware"
TESTS="$APP/lib/features/developer/rollback_test_images.g.dart"
BUILD="$(mktemp -d)"
trap 'rm -rf "$BUILD"' EXIT

OUT_DIR="$BUILD" "$ROOT/firmware/tools/build_update_image.sh"
OUT_DIR="$BUILD" "$ROOT/firmware/tools/build_update_image.sh" --rollback-test fail
OUT_DIR="$BUILD" "$ROOT/firmware/tools/build_update_image.sh" --rollback-test freeze
JSON="$(ls "$BUILD"/ElectroBright_Update-*.json)"
BIN="${JSON%.json}.bin"
[[ -f "$BIN" ]] || { echo "no update image was built" >&2; exit 1; }

mkdir -p "$DEST"
rm -f "$DEST"/*.bin "$DEST/manifest.json"
cp "$BIN" "$DEST/"
python3 - "$BUILD" "$(basename "$BIN")" "$DEST/manifest.json" "$TESTS" <<'PY'
import base64, glob, json, os, sys, zlib

build, release_file, manifest_path, tests_path = sys.argv[1:5]

def manifest(json_path, file_name):
    built = json.load(open(json_path))
    m = {
        "product": "ElectroBright",
        "kind": "universal",
        "version": built["version"],
        "size": built["size"],
        "sha256": built["sha256"],
        "file": file_name,
    }
    if built.get("rollbackTest"):
        m["rollbackTest"] = built["rollbackTest"]
    return m

release_json = os.path.join(build, release_file[:-4] + ".json")
with open(manifest_path, "w") as f:
    json.dump(manifest(release_json, release_file), f, indent=2)
    f.write("\n")

out = [
    "// GENERATED by tool/bundle_firmware.sh (firmware/tools/build_update_image.sh",
    "// --rollback-test fail|freeze). Do not edit.",
    "//",
    "// The rollback test images: zlib-compressed, base64. Only debug builds reach",
    "// this data (rollback_test.dart), so profile and release builds leave it out.",
    "// ignore_for_file: lines_longer_than_80_chars",
    "",
]
for mode in ("fail", "freeze"):
    (json_path,) = glob.glob(os.path.join(build, "ElectroBright_RollbackTest-%s-*.json" % mode))
    bin_path = json_path[:-5] + ".bin"
    m = manifest(json_path, os.path.basename(bin_path))
    data = base64.b64encode(zlib.compress(open(bin_path, "rb").read(), 9)).decode()
    name = "rollbackTestFail" if mode == "fail" else "rollbackTestFreeze"
    out.append("const String %sManifest = '%s';" % (name, json.dumps(m)))
    out.append("")
    out.append("const String %sImage =" % name)
    for i in range(0, len(data), 76):
        out.append("    '%s'" % data[i:i + 76])
    out[-1] += ";"
    out.append("")
with open(tests_path, "w") as f:
    f.write("\n".join(out))
print("   rollback test images: %s (%d KB)" % (tests_path, os.path.getsize(tests_path) // 1024))
PY
echo "   bundled into $DEST:"
cat "$DEST/manifest.json"
